# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inkoff_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ink_Dialog(object):
    def setupUi(self, Ink_Dialog):
        Ink_Dialog.setObjectName("Ink_Dialog")
        Ink_Dialog.resize(296, 662)
        self.gridLayout_4 = QtWidgets.QGridLayout(Ink_Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(Ink_Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_reset = QtWidgets.QToolButton(self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/inkoffIcon/icons8_clear_formatting.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_reset.setIcon(icon)
        self.toolButton_reset.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_reset.setObjectName("toolButton_reset")
        self.gridLayout.addWidget(self.toolButton_reset, 0, 0, 1, 1)
        self.toolButton_click = QtWidgets.QToolButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/inkoffIcon/icons8_select_none_96.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_click.setIcon(icon1)
        self.toolButton_click.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_click.setCheckable(True)
        self.toolButton_click.setObjectName("toolButton_click")
        self.gridLayout.addWidget(self.toolButton_click, 0, 1, 1, 1)
        self.toolButton_drag = QtWidgets.QToolButton(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/inkoffIcon/icons8_rectangular_4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_drag.setIcon(icon2)
        self.toolButton_drag.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_drag.setCheckable(True)
        self.toolButton_drag.setChecked(True)
        self.toolButton_drag.setObjectName("toolButton_drag")
        self.gridLayout.addWidget(self.toolButton_drag, 0, 2, 1, 1)
        self.toolButton_polygon = QtWidgets.QToolButton(self.groupBox)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/inkoffIcon/icons8_polygon_96.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_polygon.setIcon(icon3)
        self.toolButton_polygon.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_polygon.setCheckable(True)
        self.toolButton_polygon.setObjectName("toolButton_polygon")
        self.gridLayout.addWidget(self.toolButton_polygon, 0, 3, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.groupBox)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/inkoffIcon/icons8_automatic_96_1zI_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon4)
        self.toolButton.setIconSize(QtCore.QSize(32, 32))
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 0, 4, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Ink_Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox_ink_number = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_ink_number.setMinimum(1)
        self.spinBox_ink_number.setMaximum(10)
        self.spinBox_ink_number.setProperty("value", 1)
        self.spinBox_ink_number.setObjectName("spinBox_ink_number")
        self.horizontalLayout.addWidget(self.spinBox_ink_number)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.label_type = QtWidgets.QLabel(self.groupBox_2)
        self.label_type.setMinimumSize(QtCore.QSize(0, 80))
        self.label_type.setObjectName("label_type")
        self.gridLayout_2.addWidget(self.label_type, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Ink_Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_3.addWidget(self.toolButton_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.toolButton_3 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_4.addWidget(self.toolButton_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setMinimum(2)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_5.addWidget(self.spinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(150)
        self.spinBox_2.setProperty("value", 30)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_6.addWidget(self.spinBox_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 135, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 3, 0, 1, 1)

        self.retranslateUi(Ink_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Ink_Dialog)

    def retranslateUi(self, Ink_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Ink_Dialog.setWindowTitle(_translate("Ink_Dialog", "Ink Dialog"))
        self.groupBox.setTitle(_translate("Ink_Dialog", "Ink Off Tool"))
        self.toolButton_reset.setToolTip(_translate("Ink_Dialog", "rest the ink"))
        self.toolButton_reset.setText(_translate("Ink_Dialog", "..."))
        self.toolButton_click.setToolTip(_translate("Ink_Dialog", "click single die to ink"))
        self.toolButton_click.setText(_translate("Ink_Dialog", "..."))
        self.toolButton_drag.setToolTip(_translate("Ink_Dialog", "drag a square to ink"))
        self.toolButton_drag.setText(_translate("Ink_Dialog", "..."))
        self.toolButton_polygon.setToolTip(_translate("Ink_Dialog", "use polygon tool to ink"))
        self.toolButton_polygon.setText(_translate("Ink_Dialog", "..."))
        self.toolButton.setText(_translate("Ink_Dialog", "..."))
        self.groupBox_2.setTitle(_translate("Ink_Dialog", "Ink Off Rule"))
        self.label.setText(_translate("Ink_Dialog", "Ink Dies Number:"))
        self.label_2.setText(_translate("Ink_Dialog", "Ink Mode:"))
        self.comboBox.setItemText(0, _translate("Ink_Dialog", "Around Dies"))
        self.comboBox.setItemText(1, _translate("Ink_Dialog", "Cross Dies"))
        self.comboBox.setItemText(2, _translate("Ink_Dialog", "Corner Dies"))
        self.comboBox.setItemText(3, _translate("Ink_Dialog", "Any Dies"))
        self.label_type.setText(_translate("Ink_Dialog", "Type"))
        self.groupBox_3.setTitle(_translate("Ink_Dialog", "Ink Tool Setting"))
        self.label_4.setText(_translate("Ink_Dialog", "Polygon Edge Color:"))
        self.toolButton_2.setText(_translate("Ink_Dialog", "..."))
        self.label_5.setText(_translate("Ink_Dialog", "Poloygon Point Color:"))
        self.toolButton_3.setText(_translate("Ink_Dialog", "..."))
        self.label_6.setText(_translate("Ink_Dialog", "Polygon Point Number:"))
        self.label_7.setText(_translate("Ink_Dialog", "Polygon Size:"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ink_Dialog = QtWidgets.QDialog()
    ui = Ui_Ink_Dialog()
    ui.setupUi(Ink_Dialog)
    Ink_Dialog.show()
    sys.exit(app.exec_())
