# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_App_Setting_Dialog(object):
    def setupUi(self, App_Setting_Dialog):
        App_Setting_Dialog.setObjectName("App_Setting_Dialog")
        App_Setting_Dialog.resize(306, 657)
        self.gridLayout_4 = QtWidgets.QGridLayout(App_Setting_Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_wafer_layout_setting = QtWidgets.QGroupBox(App_Setting_Dialog)
        self.groupBox_wafer_layout_setting.setObjectName("groupBox_wafer_layout_setting")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_wafer_layout_setting)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_2 = QtWidgets.QLabel(self.groupBox_wafer_layout_setting)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_12.addWidget(self.label_2)
        self.toolButton_die_untest_color = QtWidgets.QToolButton(self.groupBox_wafer_layout_setting)
        self.toolButton_die_untest_color.setMinimumSize(QtCore.QSize(50, 0))
        self.toolButton_die_untest_color.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toolButton_die_untest_color.setText("")
        self.toolButton_die_untest_color.setObjectName("toolButton_die_untest_color")
        self.horizontalLayout_12.addWidget(self.toolButton_die_untest_color)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 5, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBox_die_cosmetic = QtWidgets.QCheckBox(self.groupBox_wafer_layout_setting)
        self.checkBox_die_cosmetic.setChecked(True)
        self.checkBox_die_cosmetic.setObjectName("checkBox_die_cosmetic")
        self.horizontalLayout_11.addWidget(self.checkBox_die_cosmetic)
        self.checkBox_wafer_title = QtWidgets.QCheckBox(self.groupBox_wafer_layout_setting)
        self.checkBox_wafer_title.setChecked(True)
        self.checkBox_wafer_title.setObjectName("checkBox_wafer_title")
        self.horizontalLayout_11.addWidget(self.checkBox_wafer_title)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_show_flash = QtWidgets.QCheckBox(self.groupBox_wafer_layout_setting)
        self.checkBox_show_flash.setObjectName("checkBox_show_flash")
        self.horizontalLayout_6.addWidget(self.checkBox_show_flash)
        self.checkBox_show_pass_die = QtWidgets.QCheckBox(self.groupBox_wafer_layout_setting)
        self.checkBox_show_pass_die.setObjectName("checkBox_show_pass_die")
        self.horizontalLayout_6.addWidget(self.checkBox_show_pass_die)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_die_edge_color = QtWidgets.QLabel(self.groupBox_wafer_layout_setting)
        self.label_die_edge_color.setObjectName("label_die_edge_color")
        self.horizontalLayout_3.addWidget(self.label_die_edge_color)
        self.toolButton_die_line_color = QtWidgets.QToolButton(self.groupBox_wafer_layout_setting)
        self.toolButton_die_line_color.setMinimumSize(QtCore.QSize(50, 0))
        self.toolButton_die_line_color.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.toolButton_die_line_color.setText("")
        self.toolButton_die_line_color.setObjectName("toolButton_die_line_color")
        self.horizontalLayout_3.addWidget(self.toolButton_die_line_color)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_die_line_style = QtWidgets.QLabel(self.groupBox_wafer_layout_setting)
        self.label_die_line_style.setObjectName("label_die_line_style")
        self.horizontalLayout_5.addWidget(self.label_die_line_style)
        self.comboBox_die_line_style = QtWidgets.QComboBox(self.groupBox_wafer_layout_setting)
        self.comboBox_die_line_style.setObjectName("comboBox_die_line_style")
        self.comboBox_die_line_style.addItem("")
        self.comboBox_die_line_style.addItem("")
        self.comboBox_die_line_style.addItem("")
        self.comboBox_die_line_style.addItem("")
        self.comboBox_die_line_style.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_die_line_style)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 7, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_wafer_substrate_color = QtWidgets.QLabel(self.groupBox_wafer_layout_setting)
        self.label_wafer_substrate_color.setObjectName("label_wafer_substrate_color")
        self.horizontalLayout.addWidget(self.label_wafer_substrate_color)
        self.toolButton_wafer_substrate_color = QtWidgets.QToolButton(self.groupBox_wafer_layout_setting)
        self.toolButton_wafer_substrate_color.setMinimumSize(QtCore.QSize(50, 0))
        self.toolButton_wafer_substrate_color.setStyleSheet("background-color: rgb(179, 179, 179);")
        self.toolButton_wafer_substrate_color.setText("")
        self.toolButton_wafer_substrate_color.setObjectName("toolButton_wafer_substrate_color")
        self.horizontalLayout.addWidget(self.toolButton_wafer_substrate_color)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_wafer_layout_setting)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.toolButton_flash_line_color = QtWidgets.QToolButton(self.groupBox_wafer_layout_setting)
        self.toolButton_flash_line_color.setMinimumSize(QtCore.QSize(50, 0))
        self.toolButton_flash_line_color.setStyleSheet("background-color: rgb(253, 102, 102);")
        self.toolButton_flash_line_color.setText("")
        self.toolButton_flash_line_color.setObjectName("toolButton_flash_line_color")
        self.horizontalLayout_2.addWidget(self.toolButton_flash_line_color)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_die_edge_size = QtWidgets.QLabel(self.groupBox_wafer_layout_setting)
        self.label_die_edge_size.setObjectName("label_die_edge_size")
        self.horizontalLayout_4.addWidget(self.label_die_edge_size)
        self.spinBox_die_edge_size = QtWidgets.QSpinBox(self.groupBox_wafer_layout_setting)
        self.spinBox_die_edge_size.setMinimum(1)
        self.spinBox_die_edge_size.setMaximum(10)
        self.spinBox_die_edge_size.setObjectName("spinBox_die_edge_size")
        self.horizontalLayout_4.addWidget(self.spinBox_die_edge_size)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_wafer_layout_setting, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(App_Setting_Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.plainTextEdit_wafer_title_name = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_wafer_title_name.setMaximumSize(QtCore.QSize(16777215, 50))
        self.plainTextEdit_wafer_title_name.setObjectName("plainTextEdit_wafer_title_name")
        self.verticalLayout.addWidget(self.plainTextEdit_wafer_title_name)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.spinBox_wafer_title_font = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_wafer_title_font.setMinimum(5)
        self.spinBox_wafer_title_font.setMaximum(25)
        self.spinBox_wafer_title_font.setProperty("value", 8)
        self.spinBox_wafer_title_font.setObjectName("spinBox_wafer_title_font")
        self.horizontalLayout_10.addWidget(self.spinBox_wafer_title_font)
        self.gridLayout.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_title_position_x = QtWidgets.QLabel(self.groupBox)
        self.label_title_position_x.setObjectName("label_title_position_x")
        self.horizontalLayout_9.addWidget(self.label_title_position_x)
        self.spinBox_title_pos_x = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_title_pos_x.setMinimum(-200)
        self.spinBox_title_pos_x.setMaximum(200)
        self.spinBox_title_pos_x.setProperty("value", -55)
        self.spinBox_title_pos_x.setObjectName("spinBox_title_pos_x")
        self.horizontalLayout_9.addWidget(self.spinBox_title_pos_x)
        self.label_title_position_y = QtWidgets.QLabel(self.groupBox)
        self.label_title_position_y.setObjectName("label_title_position_y")
        self.horizontalLayout_9.addWidget(self.label_title_position_y)
        self.spinBox_title_pos_y = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_title_pos_y.setMinimum(-200)
        self.spinBox_title_pos_y.setMaximum(200)
        self.spinBox_title_pos_y.setProperty("value", 180)
        self.spinBox_title_pos_y.setObjectName("spinBox_title_pos_y")
        self.horizontalLayout_9.addWidget(self.spinBox_title_pos_y)
        self.gridLayout.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_file_saving_setting = QtWidgets.QGroupBox(App_Setting_Dialog)
        self.groupBox_file_saving_setting.setObjectName("groupBox_file_saving_setting")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_file_saving_setting)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_save_ink_off_file = QtWidgets.QCheckBox(self.groupBox_file_saving_setting)
        self.checkBox_save_ink_off_file.setChecked(True)
        self.checkBox_save_ink_off_file.setObjectName("checkBox_save_ink_off_file")
        self.gridLayout_2.addWidget(self.checkBox_save_ink_off_file, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_image_resolution = QtWidgets.QLabel(self.groupBox_file_saving_setting)
        self.label_image_resolution.setObjectName("label_image_resolution")
        self.horizontalLayout_7.addWidget(self.label_image_resolution)
        self.comboBox_save_file_dpi = QtWidgets.QComboBox(self.groupBox_file_saving_setting)
        self.comboBox_save_file_dpi.setObjectName("comboBox_save_file_dpi")
        self.comboBox_save_file_dpi.addItem("")
        self.comboBox_save_file_dpi.addItem("")
        self.comboBox_save_file_dpi.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_save_file_dpi)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.toolButton_save_folder_path = QtWidgets.QToolButton(self.groupBox_file_saving_setting)
        self.toolButton_save_folder_path.setObjectName("toolButton_save_folder_path")
        self.horizontalLayout_8.addWidget(self.toolButton_save_folder_path)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_file_saving_setting)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_8.addWidget(self.lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_file_saving_setting, 2, 0, 1, 1)

        self.retranslateUi(App_Setting_Dialog)
        QtCore.QMetaObject.connectSlotsByName(App_Setting_Dialog)

    def retranslateUi(self, App_Setting_Dialog):
        _translate = QtCore.QCoreApplication.translate
        App_Setting_Dialog.setWindowTitle(_translate("App_Setting_Dialog", "Dialog"))
        self.groupBox_wafer_layout_setting.setToolTip(_translate("App_Setting_Dialog", "Wafer Layout Setting"))
        self.groupBox_wafer_layout_setting.setTitle(_translate("App_Setting_Dialog", "Wafer Layout Setting"))
        self.label_2.setText(_translate("App_Setting_Dialog", "Default Untest Die Color:"))
        self.checkBox_die_cosmetic.setToolTip(_translate("App_Setting_Dialog", "Cosmetic Plot Die"))
        self.checkBox_die_cosmetic.setText(_translate("App_Setting_Dialog", "Die Cosmetic"))
        self.checkBox_wafer_title.setText(_translate("App_Setting_Dialog", "Wafer Title"))
        self.checkBox_show_flash.setToolTip(_translate("App_Setting_Dialog", "Show Flash Dies "))
        self.checkBox_show_flash.setText(_translate("App_Setting_Dialog", "Flash Dies"))
        self.checkBox_show_pass_die.setToolTip(_translate("App_Setting_Dialog", "Show Pass Dies"))
        self.checkBox_show_pass_die.setText(_translate("App_Setting_Dialog", "Pass Dies"))
        self.label_die_edge_color.setText(_translate("App_Setting_Dialog", "Die Edge Color:"))
        self.toolButton_die_line_color.setToolTip(_translate("App_Setting_Dialog", "die edge color"))
        self.label_die_line_style.setText(_translate("App_Setting_Dialog", "Die Edge Style:"))
        self.comboBox_die_line_style.setToolTip(_translate("App_Setting_Dialog", "die line type "))
        self.comboBox_die_line_style.setItemText(0, _translate("App_Setting_Dialog", "DashLine"))
        self.comboBox_die_line_style.setItemText(1, _translate("App_Setting_Dialog", "SolidLine"))
        self.comboBox_die_line_style.setItemText(2, _translate("App_Setting_Dialog", "DashDotLine"))
        self.comboBox_die_line_style.setItemText(3, _translate("App_Setting_Dialog", "DashDotDotLine"))
        self.comboBox_die_line_style.setItemText(4, _translate("App_Setting_Dialog", "CustomerDashLine"))
        self.label_wafer_substrate_color.setText(_translate("App_Setting_Dialog", "Wafer Substrate Colors:"))
        self.toolButton_wafer_substrate_color.setToolTip(_translate("App_Setting_Dialog", "wafer substrate color"))
        self.label.setText(_translate("App_Setting_Dialog", "Flash Edge Color:"))
        self.toolButton_flash_line_color.setToolTip(_translate("App_Setting_Dialog", "flash die color "))
        self.label_die_edge_size.setText(_translate("App_Setting_Dialog", "Die Edge Size:"))
        self.spinBox_die_edge_size.setToolTip(_translate("App_Setting_Dialog", "set the die edge font "))
        self.groupBox.setTitle(_translate("App_Setting_Dialog", "Title Setting"))
        self.label_3.setText(_translate("App_Setting_Dialog", "Layout Title:"))
        self.label_4.setText(_translate("App_Setting_Dialog", "Title Font:"))
        self.label_title_position_x.setText(_translate("App_Setting_Dialog", "titile_x:"))
        self.label_title_position_y.setText(_translate("App_Setting_Dialog", "title_y:"))
        self.groupBox_file_saving_setting.setTitle(_translate("App_Setting_Dialog", "File Saving Setting"))
        self.checkBox_save_ink_off_file.setText(_translate("App_Setting_Dialog", "Save Ink Off"))
        self.label_image_resolution.setText(_translate("App_Setting_Dialog", "Image Resolution:"))
        self.comboBox_save_file_dpi.setItemText(0, _translate("App_Setting_Dialog", "100 dpi"))
        self.comboBox_save_file_dpi.setItemText(1, _translate("App_Setting_Dialog", "300 dpi"))
        self.comboBox_save_file_dpi.setItemText(2, _translate("App_Setting_Dialog", "600 dpi"))
        self.toolButton_save_folder_path.setText(_translate("App_Setting_Dialog", "Folder Path"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    App_Setting_Dialog = QtWidgets.QDialog()
    ui = Ui_App_Setting_Dialog()
    ui.setupUi(App_Setting_Dialog)
    App_Setting_Dialog.show()
    sys.exit(app.exec_())
